#!/usr/bin/perl

use lib qw(/home/tickerlick/cgi-bin);
use LWP::Simple;
use DBI;
use JSON;
use Data::Dumper;
&getResults('AAPL');
sub getResults
{
my ($ticker) = uc shift;
my (%tickhash) ;
my $url = 'https://query.yahooapis.com/v1/public/yql?q=select%20YearLow,OneyrTargetPrice,DividendShare,ChangeFromFiftydayMovingAverage,FiftydayMovingAverage,PercentChangeFromTwoHundreddayMovingAverage,DaysLow,DividendYield,ChangeFromYearLow,ChangeFromYearHigh,EarningsShare,LastTradePriceOnly,YearHigh,LastTradeDate,PreviousClose,Volume,MarketCapitalization,Name,DividendPayDate,ExDividendDate,PERatio,PercentChangeFromFiftydayMovingAverage,ChangeFromTwoHundreddayMovingAverage,DaysHigh,PercentChangeFromYearLow,TwoHundreddayMovingAverage,PercebtChangeFromYearHigh,Open,Symbol%20from%20yahoo.finance.quotes%20where%20symbol%20in%20(%22'.$ticker.'%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys&callback=';

my   $content = get($url);
if ($content)
{
my $obj = from_json($content);
if ($content =~ m/Day\'s Range<\/th><td>N\/A/)
{
 $tickhash{invalidticker} = 1;
 return %tickhash;
}
my $str = $obj->{'query'}->{'results'}->{'quote'};
print Dumper($str);
my %str1 = Dumper($str);
#my %text = decode_json(Dumper($str));
REPLACE INTO tickerpricefun (YearLow,OneyrTargetPrice,DividendShare,ChangeFromFiftydayMA,DaysLow,FiftydayMA,EarningsShare,LastTradePrice,YearHigh,LastTradeDate,Symbol,PreviousClose,Volume,PERatio,MarketCap,Name,PercentChangeFromTwoHundreddayMA,DividendPayDate,ChangeFromYearHigh,PercentChangeFromFiftydayMA,ChangeFromTwoHundreddayMA,DaysHigh,PercentChangeFromYearLow,PercebtChangeFromYearHigh,DividendYield,ChangeFromYearLow,ExDividendDate,TwoHundreddayMA,Open) values
 ($str->{'YearLow'},$str->{'OneyrTargetPrice'},$str->{'DividendShare'},$str->{'ChangeFromFiftydayMA'},$str->{'DaysLow'},$str->{'FiftydayMA'},$str->{'EarningsShare'},$str->{'LastTradePriceOnly'},$str->{'YearHigh'},$str->{'LastTradeDate'},$str->{'Symbol'},$str->{'PreviousClose'},$str->{'Volume'},$str->{'PERatio'},$str->{'MarketCap'},$str->{'Name'},$str->{'PercentChangeFromTwoHundreddayMA'},$str->{'DividendPayDate'},$str->{'ChangeFromYearHigh'},$str->{'PercentChangeFromFiftydayMA'},$str->{'ChangeFromTwoHundreddayMA'},$str->{'DaysHigh'},$str->{'PercentChangeFromYearLow'},$str->{'PercebtChangeFromYearHigh'},$str->{'DividendYield'},$str->{'ChangeFromYearLow'},$str->{'ExDividendDate'},$str->{'TwoHundreddayMA'},$str->{'Open'});
}
}
