elsif ($rep_type eq 'ef')
{
     $title = "Equity Fundamental";
     $query = "select ticker,comp_name,sector,industry,pegratio,operatingcashflow,sharesoutstanding,divyield,wkrange,mostrecentquarter,dma10diffper,qtrlyrevenuegrowth,marketcap,weekchange,prevclose,dma50diffper,difflowstat,fiscalyearends,lasttrade,payoutratio,enterprisevalueebitda,dma50stat,grossprofit,perdifflow,trailingpe,enterprisevalue,dma200,totalcashpershare,operatingmargin,pricesales,pricestat,diffhighstat,revenuepershare,pricediffper,beta,weeklow,dma10stat,netincomeavltocommon,sharesshort,pe,qtrlyearningsgrowth,enterprisevaluerevenue,pricebook,sp50052weekchange,totaldebtequity,dma200stat,nav,dma50diff,returnonassets,dilutedeps,pricediff,revenue,exdividenddate,returnonequity,dma10diff,difflow,totaldebt,class,leveredfreecashflow,yearlow,dma200diffper,weekhigh,dma10,forwardpe,dma50,dma200diff,ytargetest,ebitda,yearhigh,twohundreddaymovingaverage,currentratio,eps,diffhigh,bookvaluepershare,perdiffhigh,fiftydaymovingaverage,totalcash from secmaster a, tickermaster b where a.ticker_id = b.ticker_id and marketcap > 250000000 and pe > 0 and class = 'Common Stock' order by pe desc limit 100";
}
elsif ($rep_type eq 'nf')
{
     $title = "ETF/ETN/Fund Fundamental";
     $query = "select ticker,comp_name,sector,industry,pegratio,operatingcashflow,sharesoutstanding,divyield,wkrange,mostrecentquarter,dma10diffper,qtrlyrevenuegrowth,marketcap,weekchange,prevclose,dma50diffper,difflowstat,fiscalyearends,lasttrade,payoutratio,enterprisevalueebitda,dma50stat,grossprofit,perdifflow,trailingpe,enterprisevalue,dma200,totalcashpershare,operatingmargin,pricesales,pricestat,diffhighstat,revenuepershare,pricediffper,beta,weeklow,dma10stat,netincomeavltocommon,sharesshort,pe,qtrlyearningsgrowth,enterprisevaluerevenue,pricebook,sp50052weekchange,totaldebtequity,dma200stat,nav,dma50diff,returnonassets,dilutedeps,pricediff,revenue,exdividenddate,returnonequity,dma10diff,difflow,totaldebt,class,leveredfreecashflow,yearlow,dma200diffper,weekhigh,dma10,forwardpe,dma50,dma200diff,ytargetest,ebitda,yearhigh,twohundreddaymovingaverage,currentratio,eps,diffhigh,bookvaluepershare,perdiffhigh,fiftydaymovingaverage,totalcash from secmaster a, tickermaster b where a.ticker_id = b.ticke
